#!/bin/bash
#SBATCH --job-name=BiLSTM-DH
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --gpus-per-node=4
#SBATCH --mem=100G
#SBATCH --time=48:00:00
#SBATCH --output=test.out
#SBATCH --error=test.err
#SBATCH --partition=gpu
#SBATCH --mail-user=dhanke@ifam.uni-kiel.de
#SBATCH --mail-type=ALL

module load miniconda3/4.9.2
source /gxfs_home/cau/sunam188/.bashrc 
source activate /gxfs_work1/cau/sunam188/environments/tensorflow
python3 3_LSTMs.py